Repository klaasnicolaas/python-energyzero, pull requests merged in 2025-06, with the labels that each got.

#783 Use helper to_datetime_string for gas and energy prices
  examples/energy.py
  examples/gas.py
  src/energyzero/energyzero.py
Labels: enhancement

#777 Add timerange dataclass
  src/energyzero/__init__.py
  src/energyzero/models.py
  tests/test_models.py
Labels: new-feature

#779 Add EnergyPrices dataclass
  src/energyzero/__init__.py
  src/energyzero/const.py
  src/energyzero/models.py
  tests/fixtures/energy_ex.json
  tests/test_models.py
Labels: new-feature

#789 🔄 synced file(s) with klaasnicolaas/github-config
  .devcontainer/devcontainer.json
  .github/workflows/pr-labels.yaml
Labels: sync

#802 Refactor the old legacy vs graphql functions
  README.md
  examples/legacy/__init__.py
  examples/legacy/electricity_prices.py
  examples/legacy/gas_prices.py
  examples/legacy/prices_list.py
  src/energyzero/energyzero.py
  src/energyzero/models.py
  tests/__snapshots__/test_graphql_models.ambr
  tests/__snapshots__/test_legacy_models.ambr
  tests/fixtures/graphql/energy.json
  tests/fixtures/graphql/energy_no_prices.json
  tests/fixtures/graphql/gas.json
  tests/fixtures/graphql/gql_error.json
  tests/fixtures/graphql/no_data.json
  tests/fixtures/legacy/energy.json
  tests/fixtures/legacy/gas.json
  tests/fixtures/legacy/no_data.json
  tests/test_energyzero.py
  tests/test_graphql_models.py
  tests/test_legacy_models.py
Labels: breaking-change, refactor

#805 Remove CodeQL workflow and related badges from README
  .github/workflows/codeql.yaml
  README.md
Labels: maintenance

#808 Update workflow permissions for linting, testing, and PR validation jobs
  .github/workflows/linting.yaml
  .github/workflows/release.yaml
  .github/workflows/tests.yaml
  .github/workflows/typing.yaml
Labels: ci
